name: CI Pipeline
on:
  push:
    branches:
      - master
      - develop

env:
  DOCKER_IMAGE: chandrakantamanna/petapp:${{ github.sha }}
  MAVEN_OPTS: "-DskipTests=true"

jobs:
  setup-java:
    uses: ./.github/workflows/setup-java.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/javabuild.yml
    needs: setup-java
    secrets: inherit

  sonar:
    uses: ./.github/workflows/sonar.yml
    needs: build
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml
    needs: sonar
    secrets: inherit

  imagepush:
    uses: ./.github/workflows/imagepush.yml
    needs: test
    secrets: inherit
