name: Docker Image Build and Push

on:
  workflow_call: # Allows this workflow to be called from another workflow

jobs:
  image_push:
    runs-on: java_build # Ensure the runner is self-hosted and has the label `java_build`

    env:
      DOCKER_IMAGE: chandrakantamanna/petapp:${{ github.sha }} # Set Docker image name based on commit SHA

    steps:
      - name: Build Docker Image
        run: |
          sudo docker build -t ${{ env.DOCKER_IMAGE }} .
          sudo docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: sudo docker push ${{ env.DOCKER_IMAGE }}
