# .github/workflows/setup-java.yml
name: Set up Java

on:
  workflow_call: # Allows this workflow to be called from other workflows

jobs:
  setup-java:
    runs-on: java_build
    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
