name: Sonar Scan

on:
  workflow_call: # This allows this workflow to be called from another workflow

jobs:
  sonar:
    runs-on: java_build # Ensures it uses the self-hosted runner with the 'java_build' label

    steps:

      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=c-manna_DevSecops_Pipeline \
            -Dsonar.organization=c-manna \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_PROJECT_KEY }}
